const SECTION_TYPES = {
  'HERO_SECTION': 'HERO_SECTION',
  'TWO_CALL_TO_ACTION': 'TWO_CALL_TO_ACTION',
  'WITH_CARDS': 'WITH_CARDS', 
  'MULTIPLE_MEDIA_WITH_CAPTION': 'MULTIPLE_MEDIA_WITH_CAPTION', 
  'SINGLE_MEDIA_WITH_CAPTION_AND_PARAGRAPH': 'SINGLE_MEDIA_WITH_CAPTION_AND_PARAGRAPH', 
  'SINGLE_MEDIA_WITH_PARAGRAPH_AND_LINK': 'SINGLE_MEDIA_WITH_PARAGRAPH_AND_LINK', 
  'HEADING_WITH_SINGLE_MEDIA_AND_BUTTON': 'HEADING_WITH_SINGLE_MEDIA_AND_BUTTON',
  'REPORTS': 'REPORTS'
}

export default SECTION_TYPES